### ISSUE TITLE
[Error] runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by andreis** [hirokidaichi/goviz#3]
This is what I get. I can come back with config files if you want, but in a nutshell I'm running a pretty vanilla Mavericks with the latest go, brew, zsh, etc

```
➜  ~  goviz -i github.com/hashicorp/serf | dot -Tpng -o hoge.png
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x20ee]

goroutine 1 [running]:
runtime.panic(0x12c680, 0x2ce219)
    /usr/local/Cellar/go/1.2.1/libexec/src/pkg/runtime/panic.c:266 +0xb6
main.main()
    /Users/andrei/src/github.com/hirokidaichi/goviz/goviz.go:40 +0x7e
➜  ~  goviz -i github.com/mattn/anko | dot -Tpng -o anko.png
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x20ee]

goroutine 1 [running]:
runtime.panic(0x12c680, 0x2ce219)
    /usr/local/Cellar/go/1.2.1/libexec/src/pkg/runtime/panic.c:266 +0xb6
main.main()
    /Users/andrei/src/github.com/hirokidaichi/goviz/goviz.go:40 +0x7e
➜  ~  goviz -i github.com/dotcloud/docker/docker -m
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x20ee]

goroutine 1 [running]:
runtime.panic(0x12c680, 0x2ce219)
    /usr/local/Cellar/go/1.2.1/libexec/src/pkg/runtime/panic.c:266 +0xb6
main.main()
    /Users/andrei/src/github.com/hirokidaichi/goviz/goviz.go:40 +0x7e
```

**Comment by andreis** [comment]
@hirokidaichi An explanation would be nice.
